### ISSUE TITLE
Post filtering

### ISSUE THREAD

**Issue by scoskey** [mathtalks/settheory.mathtalks.org#8]
Support filtering posts by seminar venue or "conference". Support filtering posts by date.

**Comment by pkra** [comment]
Simplistic example: a checkbox and then e.g.,

```
      document.querySelector('#bristol').addEventListener('click', function() {
        document.querySelectorAll('[data-venue]').forEach(node => {
          if (node.getAttribute('data-venue') !== 'Bristol Logic Seminar') node.setAttribute('hidden', 'true');
        })
      } )

```

**Comment by pkra** [comment]
Master now  adds the data attributes.

**Comment by pkra** [comment]
The pure CSS filtering approach we discussed seems to work out. But we'll have to put up with 18 options.
